### ISSUE TITLE
Master-Slave Network Management

### ISSUE THREAD

**Issue by qiweimao** [qiweimao/ESP32-Datalogger#13]
Use this tutorial to add auto pairing capability: https://randomnerdtutorials.com/esp-now-auto-pairing-esp32-esp8266/

This logic can be used for ESP-NOW/LORA autopairing.

**Comment by NomiBobby** [comment]
- send request from nodes will fail, how to handle?
- gateway power cycle will lose all mac addresses and channel setting, should i add this info to nvs?

**Comment by NomiBobby** [comment]
The following functionalities still need to be developed:
- master should be able to send all logger control API to nodes
- nodes should be able to transfer readings to master
 - trunking

**Comment by NomiBobby** [comment]
Interesting read on ESP-NOW

**Comment by NomiBobby** [comment]
Interesting read on LoRa struct:
https://github.com/sandeepmistry/arduino-LoRa/issues/49

**Comment by qiweimao** [comment]
API:

1. Logger System configuration: implemented as a form.
2. Data collection configuration.

**Comment by qiweimao** [comment]
Now the problem is, data collection configuration might exceed 250 bytes, which we should avoid. Explore option to compress and decompress this.

For most sensor readings, 250 bytes will be more than enough. SAA might be a issue due to large number of nodes.

**Comment by qiweimao** [comment]
implemented
