### ISSUE TITLE
Add capability to configure the device without WiFi

### ISSUE THREAD

**Issue by qiweimao** [qiweimao/ESP32-Datalogger#3]
Read this tutorial: https://dronebotworkshop.com/wifimanager/
Github: https://github.com/tzapu/WiFiManager'

Wait for delivery of tact push button.

**Comment by NomiBobby** [comment]
Today I Read through the long tutorial above and do not see a need to include a huge library like WiFiManager. My solution is as follows:
- Add a push button to let user change WiFi modes. A task is created upon setup to detect button voltage every second.
- If button is pushed, switch WiFi mode to AP. I tested with my phone, surprisingly I can even access the web server using the new IP address without restarting the server!

Next steps: need to test if switch back to AP_STA will work. Need to verify how ESP-NOW behaves in such scenarios.

**Comment by NomiBobby** [comment]
When changing the WiFi password, I noticed that WiFi connect would block other code from executing. How to solve this?
- Make WiFi connect a non-blocking task, it should allow data logging and other tasks
-

**Comment by NomiBobby** [comment]
Sender Mode Solution: initiate the node in AP_STA as well! However, ESP_NOW long range mode needs to be turned off.

**Comment by qiweimao** [comment]
Alll devices will be set up as AP_STA to allow wifi password change via web interface.

**Comment by qiweimao** [comment]
Alll devices will be set up as AP_STA to allow wifi password change via web interface.
