### ISSUE TITLE
SD Card Instability

### ISSUE THREAD

**Issue by qiweimao** [qiweimao/ESP32-Datalogger#8]
Switched to 3v3 sd card reader, still has issues with stability.

- card crash underload, can't restart without reboot
- card speed stall to 0kb/s underload, can restart without reboot

Potential Fix
- check voltage
- check weld points
- (unlikely) reformat SD card

Useful links:
https://forum.arduino.cc/t/card-mount-failed-on-esp32-but-works-on-arduino/1096716

**Comment by NomiBobby** [comment]
SD card only works if connected to VIN & GND, does not work with 3V3.

**Comment by NomiBobby** [comment]
Solution: connect the SD card directly to the 3V3 and GND pin, turns out the cheap breadboard was the culprit!
